### ISSUE TITLE
how to get user tokens

### ISSUE THREAD

**Issue by sheub** [albertcht/lumen-vue-starter#4]
Hi albertcht,
I am building an SPA upon the Lumen-vue-starter you've written. Thanks for sharing, I find it a good basis for my work.
Now, I have added several socialite providers and I am trying to retrieve the access_tokens sent after the user has been authenticate. In other words, I would like to do something like this:
```php
        $user = Socialite::driver('google')->user();

        // Set token for the Google API PHP Client
        $google_client_token = [
            'access_token' => $user->token,
            'refresh_token' => $user->refreshToken,
            'expires_in' => $user->expiresIn
        ];
    
        $client = new Google_Client();
        $client->setApplicationName("LumenVue");
        $client->setDeveloperKey(env('GOOGLE_SERVER_KEY'));
        $client->setAccessToken(json_encode($google_client_token));
```

But Lumen being stateless, I get the error *socialite Session store not set on request*. (I am doing this to enable the visitor to manage its google account directly from my app after he logged in).

I have seen that there is a flag 'remember' in the login.vue and that a database was containing the access_token. 
But I don't know a secure way to get access to this token.
Thanks for your help

**Comment by albertcht** [comment]
Hi @sheub ,

First, since session is removed from Lumen, Socialite provides a stateless method for Lumen. You can refer to https://github.com/albertcht/lumen-vue-starter/blob/master/app/Http/Controllers/Auth/OAuthController.php

After authentication, you can get user's access token and refresh token in `oauth_providers` table.
